name       : openjml-esc          # name of the package
version    : 1.7.3.20150406-3     # version of the package
kind       : tool                 # one of tool or spec(s)
description: The Extended Static Checker for OpenJML.

author:
  - name: John L. Singleton 
    email: jsinglet@gmail.com



depends:                               
  - package   : openjml
    version   : ">= 1.7.3 && < 1.8"
    platform  : all
  - package   : z3   
    version   : ">= 4.3.0 && < 4.3.1"
    platform  : all


